HW 11
Zelourses/formal-lang-course pull request #10
Opened 2024-05-29 21:47 UTC by Zelourses

Ладно, это было просто.
Некоторый вопрос — я вот почитал в интернете, что ANTLR4 при разборе грамматик вида
```antlr
expr
  : NAME
  | expr AND expr
  | expr OR expr;
```
раскрывает его в
```antlr
expr  : NAME  | (expr AND expr) | (expr OR expr);
```
Что было немного контринтуитивно, ведь тогда надо оборачивать любое правило в кавычки
Но в то же время в офф. документации они получают нужный эффект спокойно: https://github.com/antlr/antlr4/blob/master/doc/left-recursion.md
Я в этом убедился, когда играл в antlr lab с грамматикой — всё действительно нормально парсится
Но если поставить скобки, как это написано в грамматике, то оно почему-то разваливается. Хотя по логике должно быть эквивалентным

2024-05-30 09:29 UTC, WoWaster requested changes
Тут всё хорошо, но тесты придется чинить :(

2024-05-30 09:33 UTC, WoWaster commented
Я так понимаю вопрос скорее про правило для `regexp`. Моё предположение в том, что скобочки как раз таки ломают работу с левой рекурсией у ANTLR --- как, без идей :).

2024-05-30 21:30 UTC, Zelourses commented
Как оказалось, что-то реально развалилось. И это можно было обнаружить только если удалить созданный мною в начале курса `.venv` и пересоздать его с нуля. Потому как до этого всё было ок.
В результате я исправил. Судя по всему, моя ошибка была… тупа? Я не знаю, повторится ли оно (очень сложно это сказать из-за случайности тестов) но пару перезапусков на локальной машине оно прошло полностью

2024-05-31 07:40 UTC, WoWaster commented
Всё ещё разваливается :( Но вот какие-то проблемы с 12 грамматикой я уже наблюдал у других товарищей, может быть это поможет сузить круг поиска проблемы

2024-05-31 09:54 UTC, Zelourses commented
А как у меня может падать 12 домашка, если я её даже не делал..

2024-05-31 13:17 UTC, WoWaster commented
Не домашка, а грамматика.  На 12 грамматике из списка грамматика для того теста ломается

2024-05-31 14:45 UTC, Zelourses commented
Ура, это победа

2024-05-31 15:10 UTC, WoWaster approved these changes
Поздравляю!

2024-06-01 11:40 UTC, merged