hw3
Zelourses/formal-lang-course pull request #3
Opened 2024-03-06 21:06 UTC by Zelourses

Added:
- `FiniteAutomaton` class that can be constructed from Automatons from second task
	- `FiniteAutomaton` uses sparse matrix from scipy

Changed:
- header of tests, now they are compiling

2024-03-06 21:07 UTC, Zelourses commented
Прошу прощения, сегодня позже отправил. Сложная неделя выдалась

2024-03-07 18:45 UTC, WoWaster requested changes
Тесты проходят и это замечательно, но вот функцию `paths_ends` вы не реализовали :(

2024-03-08 18:19 UTC, Zelourses commented
Я увидел что тесты проходят и обрадовался, и напрочь забыл о `paths_ends`
Сейчас добавил

2024-03-08 20:06 UTC, WoWaster approved these changes

2024-03-13 14:37 UTC, merged